AllCops:
  TargetRubyVersion: 2.2

Lint/AssignmentInCondition:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Metrics/LineLength:
  Max: 120

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/Documentation:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma
